name: GitOps Pipeline with ArcgoCD

on:
    push:
        branches:
            - main 
env:
    PERSONAL_ACTIONS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with: 
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                fetch-depth: 0
            
